### ISSUE TITLE
Error loading stream

### ISSUE THREAD

**Issue by shanethegooner** [nonvegan/streamlink-plugin-kick#3]
Hi, thanks for the plugin but I'm having issues loading Kick streams, plugin is installed into AppData\Roaming\streamlink\plugins, running Streamlink 5.3.1 and I've installed cloudscraper.

C:\Users\xxxx\Desktop>streamlink https://kick.com/xxxxxx best
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 881, in main
    setup_plugins(args.plugin_dirs)
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 697, in setup_plugins
    load_plugins(PLUGIN_DIRS, showwarning=False)
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 611, in load_plugins
    success = streamlink.load_plugins(str(directory))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\session.py", line 617, in load_plugins
    mod = load_module(module_name, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sodwy\AppData\Roaming\streamlink\plugins\kick.py", line 74
    <title>streamlink-plugin-kick/kick.py at master · nonvegan/streamlink-plugin-kick</title>
                                                    ^
SyntaxError: invalid character '·' (U+00B7)

Any ideas? Thanks!

**Comment by nonvegan** [comment]
Looks like you accidentally downloaded the html webpage instead of the actual plugin raw file. Can you check if that's the case?

**Comment by shanethegooner** [comment]
I think I might have, I copied the raw file instead but still get an error. 

C:\Users\sodwy\Desktop>streamlink https://kick.com/xxxx best
[session][error] Failed to load plugin kick from C:\Users\sodwy\AppData\Roaming\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files\Streamlink\pkgs\streamlink\session.py", line 617, in load_plugins
    mod = load_module(module_name, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sodwy\AppData\Roaming\streamlink\plugins\kick.py", line 8, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'
error: No plugin can handle URL: https://kick.com/xxxx

cloudscraper is installed. 

![image](https://user-images.githubusercontent.com/78965087/229853575-11a22357-0338-491a-a2d6-d3577c4fa6bb.png)

**Comment by nonvegan** [comment]
Hmnnn, that's the same issue as #2... Can you try ```python -m pip install cloudscraper``` and see if that fixes it?

**Comment by shanethegooner** [comment]
Doesn't appear so. I removed cloudscraper and re-installed it, same error.

![image](https://user-images.githubusercontent.com/78965087/229857835-b581bf36-5bbe-4f57-88e3-7cbc6d0fa2cd.png)

**Comment by nonvegan** [comment]
I think I might know why this is happening. So the streamlink windows builds come bundled with their own embedded Python environment, so this would explain why it's not finding the module installed via pip.

**Comment by shanethegooner** [comment]
Ah, that was it! I copied cloudscraper and requests_toolbelt into C:\Program Files\Streamlink\pkgs and now it's all working. Thanks!

**Comment by nonvegan** [comment]
Sweet!
