### ISSUE TITLE
TypeError: pluginmatcher() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by bleedingpixels** [nonvegan/streamlink-plugin-kick#4]
PS C:\Windows\System32> streamlink kick.com/video/bc5ad9f9-1f6c-414d-8ff8-f540f3ddcdea best
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 927, in main
    setup_streamlink()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 751, in setup_streamlink
    streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 96, in __init__
    self.load_builtin_plugins()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 437, in load_builtin_plugins
    self.load_plugins(plugins.__path__[0])
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 453, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\kick.py", line 21, in <module>
    @pluginmatcher(
TypeError: pluginmatcher() got an unexpected keyword argument 'name'

anyone use this plugin lately?

**Comment by nonvegan** [comment]
Are you using the latest streamlink version?

**Comment by bleedingpixels** [comment]
ah, that was the problem, now I have that Captcha error #1  :(

**Comment by nonvegan** [comment]
Nice! Unfortunately, as far as I'm aware there's no straight forwarder solution until KICK launches an official dev api :(
